ARG EE_BASE_IMAGE=registry.redhat.io/ansible-automation-platform-21/ee-supported-rhel8
ARG EE_BUILDER_IMAGE=registry.redhat.io/ansible-automation-platform-21/ansible-builder-rhel8

FROM $EE_BASE_IMAGE as galaxy
ARG ANSIBLE_GALAXY_CLI_COLLECTION_OPTS=
USER root

ADD _build /build
WORKDIR /build


FROM $EE_BUILDER_IMAGE as builder
ADD _build/bindep.txt bindep.txt
RUN ansible-builder introspect --sanitize --user-bindep=bindep.txt --write-bindep=/tmp/src/bindep.txt --write-pip=/tmp/src/requirements.txt
ADD pip.conf /etc/pip.conf
RUN rm /etc/yum.repos.d/ubi.repo
RUN assemble

FROM $EE_BASE_IMAGE
USER root
ADD pip.conf /etc/pip.conf
RUN pip3 install setuptools-scm
RUN rm /etc/yum.repos.d/ubi.repo && microdnf install -y gcc python38-devel libssh-devel
COPY --from=builder /output/ /output/
RUN /output/install-from-bindep && rm -rf /output/wheels
RUN update-crypto-policies --set DEFAULT:AD-SUPPORT && update-crypto-policies --show && microdnf remove gcc
