---
version: 1
# Test 7

build_arg_defaults:
  EE_BASE_IMAGE: 'registry.redhat.io/ansible-automation-platform-21/ee-29-rhel8'
  EE_BUILDER_IMAGE: 'registry.redhat.io/ansible-automation-platform-21/ansible-builder-rhel8'

dependencies:
  python: py3_ansible29_requirements.txt
  galaxy: requirements.yml
  system: bindep.txt
