---
version: 1

build_arg_defaults:
  EE_BASE_IMAGE: 'registry.redhat.io/ansible-automation-platform-21/ee-supported-rhel8'
  EE_BUILDER_IMAGE: 'registry.redhat.io/ansible-automation-platform-21/ansible-builder-rhel8'

dependencies:
  system: bindep.txt

additional_build_steps:
  prepend:
    - ADD pip.conf /etc/pip.conf
    - RUN pip3 install setuptools-scm
    - RUN rm /etc/yum.repos.d/ubi.repo && microdnf install -y gcc python38-devel libssh-devel
  append:
    - RUN update-crypto-policies --set DEFAULT:AD-SUPPORT && update-crypto-policies --show && microdnf remove gcc
