---
version: 1
# Test rhel8

build_arg_defaults:
  EE_BASE_IMAGE: 'registry.redhat.io/ansible-automation-platform-23/ee-supported-rhel8'
  EE_BUILDER_IMAGE: 'registry.redhat.io/ansible-automation-platform-23/ansible-builder-rhel8'

dependencies:
  python: requirements.txt
  galaxy: requirements.yml
#  system: bindep.txt
